version: "3.9"

services:
  database: 
    image: postgres
    container_name: database_memories
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=memories
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: memories
    restart: always
    environment:
        - LOGGER=1
        - JWT_SECRET="DSADMSANDJSADJSASNndsdndsdnjsdnjlslsskoddnflposaposamdksalamcklan"
        - DATABASE_URL="postgresql://docker:docker@localhost:5432/memories?schema=public"
        - PORT=3333
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local