PUT http://localhost:3333/api/memories/97f6d797-d528-4772-9eb0-c973e047006b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YTJlMjVlMC1kMjNlLTRlMmItOWNhOS1hMmRjYjBiNTc3MjQiLCJpYXQiOjE2ODQ4NjkwMTd9.3wxHQQKoOd8MzlsCjvrMVE4cKtJI9prhpMQwV1WKQ54

{
  "description": "Lorem Ipsum is simply dummy text of the"
}